# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       nextcloud-client

# >> macros
# << macros

Summary:    Nextcloud command line sync client
Version:    2.6.4
Release:    0
Group:      Applications
License:    GPLv2
URL:        https://github.com/nextcloud/desktop
Source0:    %{name}-%{version}.tar.gz
Source100:  nextcloud-client.yaml
Patch0:     no-webengine.patch
Patch1:     no-gui-2.6.4.patch
BuildRequires:  pkgconfig(openssl) >= 1.1
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(sqlite3)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Svg)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5WebKitWidgets)
BuildRequires:  pkgconfig
BuildRequires:  cmake
BuildRequires:  qt5-qttools-linguist
BuildRequires:  qt5-qmake
BuildRequires:  qtkeychain-devel

%description
%{summary}.

NOTE: The library installs in /usr/lib/nextcloud for compatability reasons with OwnCloud.
This means you will have to have that path in your LD_LIBRARY_PATH variable to use the client.

%if "%{?vendor}" == "chum"
PackageName: Nextcloud Sync Client
Type: console-application
PackagerName: nephros
Categories:
 - Utility
 - FileTools
 - NetworkFilesystems
Custom:
  Repo: https://github.com/nextcloud/desktop
  PackagingRepo: https://gitlab.com/nephros/nextcloud-client
Icon: https://avatars.githubusercontent.com/u/19211038?s=200&v=4
Url:
  Homepage: https://nextcloud.com/install/#install-clients
  Help: https://gitlab.com/nephros/nextcloud-client/-/blob/%{version}/README_SailfishOS.md
%endif


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name}-libs = %{version}-%{release}

%description devel
%{summary}.


%package libs
Summary:    Libraries for %{name}
Group:      Development/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libs
%{summary}.

%if "%{?vendor}" == "chum"
PackageName: Nextcloud Client Libraries
PackagerName: nephros
Categories:
 - Library
Custom:
  Repo: https://github.com/nextcloud/desktop
  PackagingRepo: https://gitlab.com/nephros/nextcloud-client
Icon: https://avatars.githubusercontent.com/u/19211038?s=200&v=4
Url:
  Homepage: https://nextcloud.com/install/#install-clients
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# no-webengine.patch
%patch0 -p1
# no-gui-2.6.4.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DBUILD_SHELL_INTEGRATION=0 \
    -DBUILD_SHELL_INTEGRATION_DOLPHIN=0 \
    -DBUILD_SHELL_INTEGRATION_ICONS=0 \
    -DBUILD_SHELL_INTEGRATION_NAUTILUS=0 \
    -DNO_SHIBBOLETH=1

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post libs -p /sbin/ldconfig

%postun libs -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%license COPYING
%config %{_sysconfdir}/Nextcloud/*
%{_bindir}/*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/*
%{_libdir}/*.so
%{_libdir}/*/*.so
# << files devel

%files libs
%defattr(-,root,root,-)
# >> files libs
%{_libdir}/*.so.*
%{_libdir}/*/*.so.*
# << files libs
