# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.34.2
# 

Name:       nextcloud-client

# >> macros
# << macros

Summary:    Nextcloud command line sync client
Version:    3.14.1
Release:    0
Group:      Applications
License:    GPLv2
URL:        https://github.com/nextcloud/desktop
Source0:    %{name}-%{version}.tar.gz
Source1:    libssl-1.0.patch
Source100:  nextcloud-client.yaml
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(sqlite3)
BuildRequires:  pkgconfig(Qt6Concurrent)
BuildRequires:  pkgconfig(Qt6Core)
BuildRequires:  pkgconfig(Qt6Core5Compat)
BuildRequires:  pkgconfig(Qt6DBus)
BuildRequires:  pkgconfig(Qt6Gui)
BuildRequires:  pkgconfig(Qt6Linguist)
BuildRequires:  pkgconfig(Qt6QmlCompiler)
BuildRequires:  pkgconfig(Qt6Quick)
BuildRequires:  pkgconfig(Qt6Svg)
BuildRequires:  pkgconfig(Qt6WebSockets)
BuildRequires:  pkgconfig(Qt6Xml)
BuildRequires:  pkgconfig
BuildRequires:  cmake
BuildRequires:  qt6-qtkeychain-devel
BuildRequires:  qt6-rpm-macros
BuildRequires:  qt6-qttools
BuildRequires:  kf6-karchive-devel

%description
%{summary}.

NOTE: The library installs in /usr/lib/nextcloud for compatability reasons with OwnCloud.
This means you will have to have that path in your LD_LIBRARY_PATH variable to use the client.

%if "%{?vendor}" == "chum"
Title: Nextcloud Sync Client (Qt6)
Type: console-application
PackagedBy: nephros
Categories:
 - Utility
 - FileTools
 - NetworkFilesystems
Custom:
  Repo: https://github.com/nextcloud/desktop
  PackagingRepo: https://gitlab.com/nephros/nextcloud-client
Icon: https://avatars.githubusercontent.com/u/19211038?s=200&v=4
Url:
  Homepage: https://nextcloud.com/install/#install-clients
  Help: https://gitlab.com/nephros/nextcloud-client/-/blob/%{version}/README_SailfishOS.md
%endif


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name}-libs = %{version}-%{release}

%description devel
%{summary}.


%package libs
Summary:    Libraries for %{name}
Group:      Development/Libraries

%description libs
%{summary}.

%if "%{?vendor}" == "chum"
Title: Nextcloud Client Libraries
PackagedBy: nephros
Categories:
 - Library
Custom:
  Repo: https://github.com/nextcloud/desktop
  PackagingRepo: https://gitlab.com/nephros/nextcloud-client
Icon: https://avatars.githubusercontent.com/u/19211038?s=200&v=4
Url:
  Homepage: https://nextcloud.com/install/#install-clients
%endif


%define spectacle_hack_starts here
# add a conditional dep:
%if 0%{?sailfishos_version} <= 40500
BuildRequires:  pkgconfig(Qt5WebKitWidgets)
%endif
%define spectacle_hack_ends here

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
%if %{sailfishos_version} < 40001
patch -p1 < %SOURCE1
%endif
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_INSTALL_LIBDIR=%{_libdir}/nextcloud \
    -DTOKEN_AUTH_ONLY=OFF \
    -DBUILD_SHELL_INTEGRATION=OFF \
    -DBUILD_SHELL_INTEGRATION_ICONS=OFF \
    -DBUILD_SHELL_INTEGRATION_DOLPHIN=OFF \
    -DBUILD_SHELL_INTEGRATION_NAUTILUS=OFF \
    -DBUILD_GUI=OFF \
    -DBUILD_TESTING=OFF \
    -DBUILD_WITH_WEBENGINE=OFF


# >> build post
%cmake_build
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
%cmake_install
# << install post

%files
%defattr(-,root,root,-)
%config %{_sysconfdir}/Nextcloud/*
%{_bindir}/nextcloudcmd
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%license COPYING
%{_includedir}/nextcloudsync/
%{_libdir}/nextcloud/*.so
# >> files devel
# << files devel

%files libs
%defattr(-,root,root,-)
%{_libdir}/nextcloud/*.so.*
# >> files libs
# << files libs
