# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       template-app

# >> macros
# << macros

Summary:    Template Project
Version:    0.9.0
Release:    0
Group:      Applications
License:    Apache-2.0
URL:        
Source0:    %{name}-%{version}.tar.gz
Source100:  template-app.yaml
Requires:   libsailfishapp-launcher
BuildRequires:  qt5-qttools-linguist
BuildRequires:  desktop-file-utils

%description


%if "%{?vendor}" == "chum"
PackageName: Advanced Camera
Type: desktop-application
DeveloperName: Peter G.
DeveloperLogin: nephros
PackagerName: nephros
Categories:
 - Media
 - Video
Custom:
  Repo: https://github.com/nephros/template
Icon: https://raw.githubusercontent.com/nephros/harbour-template/master/icons/template.svg
Screenshots:
 - https://github.com/nephros/nephros/raw/metadata/screenshots/screenshot1.png
 - https://github.com/nephros/nephros/raw/metadata/screenshots/screenshot2.png
 - https://github.com/nephros/nephros/raw/metadata/screenshots/screenshot3.png
Url:
  Homepage: https://github.com/nephros/template
  Help: https://github.com/nephros/template/discussions
  Bugtracker: https://github.com/nephros/template/issues
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%license LICENSE
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/*/*/apps/%{name}.png
%{_datadir}/icons/*/*/apps/%{name}.svg
%{_datadir}/%{name}/translations/*.qm
%{_datadir}/%{name}/qml/*
# >> files
# << files
